{% set name = "intel-vaapi-driver" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/intel/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.bz2
  sha1: 89096f99da753ac5858304e6c17f5dd9e7581d5b

build:
  skip: True  # [not linux]
  number: 0
  # https://github.com/intel/intel-vaapi-driver/blob/master/NEWS
  run_exports:
    - {{ pin_subpackage('intel-vaapi-driver', max_pin='x.x') }}
  script:
    - ./configure --prefix=$PREFIX --enable-hybrid-codec
    - make -j$(nproc) install

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
  host:
    - intel-hybrid-driver

test:
  commands:
    - test -f $PREFIX/lib/dri/i965_drv_video.so

about:
  home: https://github.com/intel/intel-vaapi-driver
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'VA-API (Video Acceleration API) user mode driver for Intel GEN Graphics family'

  # The remaining entries in this section are optional, but recommended
  description: |
    VA-API is an open-source library and API specification, which provides
    access to graphics hardware acceleration capabilities for video processing.
    It consists of a main library and driver-specific acceleration backends for
    each supported hardware vendor.

    The current video driver backend provides a bridge to the GEN GPUs through
    the packaging of buffers and commands to be sent to the i915 driver for
    exercising both hardware and shader functionality for video decode, encode,
    and processing.

extra:
  recipe-maintainers:
    - hmaarrfk
