appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: jV5xZWx4glDeUeQymFOeOEmfgYeMMyqDvoolCBIXJXpSxuswvbnjsUc7xZMf0AZiHRvAfBOIBava0J2ySFWQ4F2Il5IBLfK/sekiFvBa1489oKc6xfV7OFQxbfjswiu3Jsy0SZ5aNYtqk43cdczJOVa9Gs0Qh5a+o6rNehQCzc7pomhrrO1iwwfKSAVOp6ih/TJ7u5v21uCAmavZ2a7XH8LBviVfiJV+9cLh7+boh0zotKOh7kjS9+rcThAxiYulQDTtfVPQCKvjwKReDNo/+wog7D6XprU9btD2LtyDuZsSwVe3ujxcam3P+Lj8frm5fNJKs4Zq/kwoRf2+If7DXezK0xfCZb5bva5Hyq9DrN9zc5W00Z1O7Nuk5sXu2V3bRg/NDsw2lbYreMP/XM+GyP55AzhCyBHQpKe9/oG53gozALuIxvcphyXlx5Uva5T/6lkdYb4X84kzPNzaMEnFPhoBfSngCe9l+yxTYAE0lE4cRDhr1KD+SncChDM8ELz5D5PhhH9VKCIRSSSMZUuIJDSCSHftnglS+XMhjbdHaTvk//Vvo60p6hZpWvSJ03+9maORWKoZpQfF5LcXlsiwQcOMc1paWOQnfNs7OH93dHpzwlebqpzGjOM94gror+EBHOM6lH0Y9KVeHOaKcUaBJrZ0aXGIJ0eJajqfzhfy4zk=}
